name: py_snowpark_llm
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - pip:
    # Snowpark
    - snowflake-snowpark-python[pandas]==1.6.1
    - snowflake-ml-python==1.0.5
    # Basics
    - pandas==1.5.3
    - numpy==1.23.5
    # LLM/ML
    - openai
    - scikit-llm==0.3.4
    - scikit-learn==1.2.2
    - lightgbm==3.3.5
    - xgboost==1.7.3
    # Visualization
    - seaborn==0.12.2
    - matplotlib==3.7.1
    # Misc
    - cloudpickle==2.0.0
    - jupyter==1.0.0
